import gspread
from oauth2client.service_account import ServiceAccountCredentials




def dataframe(link='https://www.googleapis.com/auth/drive',name_json='GraphicsCOVID19.json'):


    scope = [link]
    credentials = ServiceAccountCredentials.from_json_keyfile_name(name_json, scope)
    client = gspread.authorize(credentials)

    return client



def states_sheets(states,index):
    state = [['Rio Grande do Sul',
              'https://docs.google.com/spreadsheets/d/1HCIHA9q5-CHmVwX1lGiCLthjmkQSigRHVFHax8joqdc/edit#gid=448824465',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_grande_do_sul.xls'],
             ['Santa Catarina',
              'https://docs.google.com/spreadsheets/d/1zC32onT-JuvjD0CR37kDfOVqE9FXx5PjtjFAIU8k7jg/edit#gid=885214190',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_santa_catarina.xls'],
             ['Paraná',
              'https://docs.google.com/spreadsheets/d/14uItnIa4mSgbxhwP43li0amdnp-YWtTx7M0T7-JRm98/edit?usp=drive_web&ouid=107070199590713527729',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_parana.xls'],
             ['São Paulo',
              'https://docs.google.com/spreadsheets/d/14uItnIa4mSgbxhwP43li0amdnp-YWtTx7M0T7-JRm98/edit?usp=drive_web&ouid=107070199590713527729',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_sao_paulo.xls'],
             ['Rio de Janeiro',
              'https://docs.google.com/spreadsheets/d/17ep4vuyJPU1aI5IRGdYTyKz08G0E9y-YcUl7YiUbdX8/edit#gid=63005548',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_de_janeiro.xls'],
             ['Espírito Santo',
              'https://docs.google.com/spreadsheets/d/1XMQR216vXCHSuJj0ZsUycHotXIJH4Z_bDGyTMaiYlLI/edit#gid=1748272040',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_espirito_santo.xls'],
             ['Minas Gerais',
              'https://docs.google.com/spreadsheets/d/1KxbDZoL85YSrJCJRpfYqoMiUt08V0y-4n6xrGERHvrk/edit#gid=965247181',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_minas_gerais.xls'],
             ['Bahia',
              'https://docs.google.com/spreadsheets/d/1rLUEGm3gxf9nyLleOeF6V_xkwhDZg4phDEOrawEhnp0/edit#gid=42601483',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_bahia.xls'],
             ['Sergipe', 'https://docs.google.com/spreadsheets/d/1TrsHoL2-3yT0iL0YKbP-ZSDLGDCYGJIaJZuIgPSkhGI/edit',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_sergipe.xls'],
             ['Alagoas',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_alagoas.xls'],
             ['Pernambuco',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_pernambuco.xls'],
             ['Paraíba',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_paraiba.xls'],
             ['Rio Grande do Norte',
              'https://docs.google.com/spreadsheets/d/1GipIOuIZ5bGoM_31RqZO9t-FZ7jncQFOy6MHP6nX8_4/edit#gid=2078102645',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_grande_do_norte.xls'],
             ['Ceará',
              'https://docs.google.com/spreadsheets/d/1Y0qyUKlBMeQpdzg94jeOP_8QsqdprKNQCqUR3KaQGTc/edit#gid=1549314560',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_ceara.xls'],
             ['Piauí',
              'https://docs.google.com/spreadsheets/d/1Ym7GJCEzu31WifRNWGXmthbl6dCDt2qCZaWByK8jJgk/edit#gid=1785988979',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_piaui.xls'],
             ['Maranhão',
              'https://docs.google.com/spreadsheets/d/1j-Yuh9bLhsNKuOG-BQ-IrONZcnlk8k3ruVXffagl3mA/edit#gid=1626150051',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_maranhao.xls'],
             ['Tocantins',
              'https://docs.google.com/spreadsheets/d/1SPlFflVD_HzzjzU1-FgrEbFHSfDnAN_5SXJvs7wO5sg/edit#gid=1868135444',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_tocantins.xls'],
             ['Pará',
              'https://docs.google.com/spreadsheets/d/1SPlFflVD_HzzjzU1-FgrEbFHSfDnAN_5SXJvs7wO5sg/edit#gid=1868135444',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_para.xls'],
             ['Amapá',
              'https://docs.google.com/spreadsheets/d/1vWJtBL1F8b9UmCjkxZat9jFF_d-MOgwZp60lJ_CyP9c/edit#gid=1482758049',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_amapa.xls'],
             ['Roraima',
              'https://docs.google.com/spreadsheets/d/1CTKkAbvKlxD_o70ibucjMneRN3qLPTK2TBhkaxpZg_U/edit#gid=1326562910',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_roraima.xls'],
             ['Amazonas',
              'https://docs.google.com/spreadsheets/d/1_Xa0_DYFAEzFurJmAwiSAcusWr09aznyh7VTPsKmrx4/edit#gid=1614829244',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_amazonas.xls'],
             ['Acre',
              'https://docs.google.com/spreadsheets/d/1-iMWE9U4QM0r88qUWB1L9pTeJmtc-SgJN3_BF9QYKfI/edit#gid=748263213',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_acre.xls'],
             ['Rondônia',
              'https://docs.google.com/spreadsheets/d/1uzewUQCqfdAbYD4GEO1RJGeIqB4sI_4oOmmfhvPRL3Y/edit#gid=1234023774',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rondonia.xls'],
             ['Mato Grosso',
              'https://docs.google.com/spreadsheets/d/1ZR7X4mqZvRsrFKnVagDcXW7i4MKzweLoT3AxIeYgnD8/edit#gid=1159051306',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_mato_grosso_do_sul.xls'],
             ['Mato Grosso do Sul',
              'https://docs.google.com/spreadsheets/d/1sQ4mMQVqH2ssfuzHkD1jGr5eofblpyWOTpUOPRxxM0s/edit#gid=473149339',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_mato_grosso.xls'],
             ['Goiás',
              'https://docs.google.com/spreadsheets/d/1G0qR3b6fgRRidgMFZtwHH3jrIuA4BwP4RFWFgxJhZI8/edit#gid=293254907',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_goias.xls'],
             'Distrito Federal',
             'https://docs.google.com/spreadsheets/d/1v4Fns0czErg5bz7SseHgPcI1v-rD3MV60DVEJuTmfI8/edit#gid=76014066',
             'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_distrito_federal.xls']
    return state[states][index]

def state_len():
    state = [['Rio Grande do Sul',
              'https://docs.google.com/spreadsheets/d/1HCIHA9q5-CHmVwX1lGiCLthjmkQSigRHVFHax8joqdc/edit#gid=448824465',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_grande_do_sul.xls'],
             ['Santa Catarina',
              'https://docs.google.com/spreadsheets/d/1zC32onT-JuvjD0CR37kDfOVqE9FXx5PjtjFAIU8k7jg/edit#gid=885214190',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_santa_catarina.xls'],
             ['Paraná',
              'https://docs.google.com/spreadsheets/d/14uItnIa4mSgbxhwP43li0amdnp-YWtTx7M0T7-JRm98/edit?usp=drive_web&ouid=107070199590713527729',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_parana.xls'],
             ['São Paulo',
              'https://docs.google.com/spreadsheets/d/14uItnIa4mSgbxhwP43li0amdnp-YWtTx7M0T7-JRm98/edit?usp=drive_web&ouid=107070199590713527729',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_sao_paulo.xls'],
             ['Rio de Janeiro',
              'https://docs.google.com/spreadsheets/d/17ep4vuyJPU1aI5IRGdYTyKz08G0E9y-YcUl7YiUbdX8/edit#gid=63005548',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_de_janeiro.xls'],
             ['Espírito Santo',
              'https://docs.google.com/spreadsheets/d/1XMQR216vXCHSuJj0ZsUycHotXIJH4Z_bDGyTMaiYlLI/edit#gid=1748272040',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_espirito_santo.xls'],
             ['Minas Gerais',
              'https://docs.google.com/spreadsheets/d/1KxbDZoL85YSrJCJRpfYqoMiUt08V0y-4n6xrGERHvrk/edit#gid=965247181',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_minas_gerais.xls'],
             ['Bahia',
              'https://docs.google.com/spreadsheets/d/1rLUEGm3gxf9nyLleOeF6V_xkwhDZg4phDEOrawEhnp0/edit#gid=42601483',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_bahia.xls'],
             ['Sergipe', 'https://docs.google.com/spreadsheets/d/1TrsHoL2-3yT0iL0YKbP-ZSDLGDCYGJIaJZuIgPSkhGI/edit',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_sergipe.xls'],
             ['Alagoas',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_alagoas.xls'],
             ['Pernambuco',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_pernambuco.xls'],
             ['Paraíba',
              'https://docs.google.com/spreadsheets/d/1Ty12Dkm_BB4nRwTFz-4mGRDjYmtv4XZWzj8xJ7WwfYQ/edit#gid=610872440',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_paraiba.xls'],
             ['Rio Grande do Norte',
              'https://docs.google.com/spreadsheets/d/1GipIOuIZ5bGoM_31RqZO9t-FZ7jncQFOy6MHP6nX8_4/edit#gid=2078102645',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rio_grande_do_norte.xls'],
             ['Ceará',
              'https://docs.google.com/spreadsheets/d/1Y0qyUKlBMeQpdzg94jeOP_8QsqdprKNQCqUR3KaQGTc/edit#gid=1549314560',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_ceara.xls'],
             ['Piauí',
              'https://docs.google.com/spreadsheets/d/1Ym7GJCEzu31WifRNWGXmthbl6dCDt2qCZaWByK8jJgk/edit#gid=1785988979',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_piaui.xls'],
             ['Maranhão',
              'https://docs.google.com/spreadsheets/d/1j-Yuh9bLhsNKuOG-BQ-IrONZcnlk8k3ruVXffagl3mA/edit#gid=1626150051',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_maranhao.xls'],
             ['Tocantins',
              'https://docs.google.com/spreadsheets/d/1SPlFflVD_HzzjzU1-FgrEbFHSfDnAN_5SXJvs7wO5sg/edit#gid=1868135444',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_tocantins.xls'],
             ['Pará',
              'https://docs.google.com/spreadsheets/d/1SPlFflVD_HzzjzU1-FgrEbFHSfDnAN_5SXJvs7wO5sg/edit#gid=1868135444',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_para.xls'],
             ['Amapá',
              'https://docs.google.com/spreadsheets/d/1vWJtBL1F8b9UmCjkxZat9jFF_d-MOgwZp60lJ_CyP9c/edit#gid=1482758049',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_amapa.xls'],
             ['Roraima',
              'https://docs.google.com/spreadsheets/d/1CTKkAbvKlxD_o70ibucjMneRN3qLPTK2TBhkaxpZg_U/edit#gid=1326562910',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_roraima.xls'],
             ['Amazonas',
              'https://docs.google.com/spreadsheets/d/1_Xa0_DYFAEzFurJmAwiSAcusWr09aznyh7VTPsKmrx4/edit#gid=1614829244',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_amazonas.xls'],
             ['Acre',
              'https://docs.google.com/spreadsheets/d/1-iMWE9U4QM0r88qUWB1L9pTeJmtc-SgJN3_BF9QYKfI/edit#gid=748263213',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_acre.xls'],
             ['Rondônia',
              'https://docs.google.com/spreadsheets/d/1uzewUQCqfdAbYD4GEO1RJGeIqB4sI_4oOmmfhvPRL3Y/edit#gid=1234023774',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_rondonia.xls'],
             ['Mato Grosso',
              'https://docs.google.com/spreadsheets/d/1ZR7X4mqZvRsrFKnVagDcXW7i4MKzweLoT3AxIeYgnD8/edit#gid=1159051306',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_mato_grosso_do_sul.xls'],
             ['Mato Grosso do Sul',
              'https://docs.google.com/spreadsheets/d/1sQ4mMQVqH2ssfuzHkD1jGr5eofblpyWOTpUOPRxxM0s/edit#gid=473149339',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_mato_grosso.xls'],
             ['Goiás',
              'https://docs.google.com/spreadsheets/d/1G0qR3b6fgRRidgMFZtwHH3jrIuA4BwP4RFWFgxJhZI8/edit#gid=293254907',
              'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_goias.xls'],
             'Distrito Federal',
             'https://docs.google.com/spreadsheets/d/1v4Fns0czErg5bz7SseHgPcI1v-rD3MV60DVEJuTmfI8/edit#gid=76014066',
             'C:/Users/weime/Documents/Estudo/Engenharia Biomédica/Modelo COVID/total_populacao_distrito_federal.xls']
    return len(state)



